# Generated by Django 5.2.7 on 2026-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cv_file_path',
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv_file',
            field=models.FileField(blank=True, help_text='CV PDF file', null=True, upload_to='candidates/cvs/'),
        ),
    ]
