# Generated by Django 5.2.7 on 2026-01-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_change_cv_to_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Job title (e.g., Senior Python Developer)', max_length=255)),
                ('description', models.TextField(help_text='Full job description text')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('embedding_id', models.CharField(blank=True, help_text='Reference ID in ChromaDB', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_id'], name='documents_j_job_id_52daa3_idx'), models.Index(fields=['embedding_processed'], name='documents_j_embeddi_b0f28a_idx'), models.Index(fields=['created_at'], name='documents_j_created_374e44_idx')],
            },
        ),
    ]
